apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition # your own resource definition name, which is used by k8s
metadata: # it's the url for your own resource, rule: {spec.names.plural}.{spec.group}
  name: myresources.trstringer.com
spec: # define your own basic resource (for api part, and resource struct name)
  group: trstringer.com
  version: v1
  names:
    kind: MyResource # Resource struct name in code, you should define resource detail info in other yaml file
    plural: myresources
  scope: Namespaced
